# Generated by Django 6.0.7 on 2026-08-04 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('cell_number', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('Admin', 'Administrator'), ('Receptionist', 'Receptionist'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Pharmacist', 'Phamacist')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
